### ISSUE TITLE
融合图像信息缺失

### ISSUE THREAD

**Issue by ShirlySmile** [GigaVision/PANDA-Toolkit#1]
您好，冒昧打扰。我在使用代码过程中发现，在将切分后小图的标注信息融合过程中，是否丢失了人检测框的一部分信息。该问题具体在panda_utils.py文件的190-200行？万分期待您的回复。

**Comment by DarkstartsUp** [comment]
I'm the project developer, thanks for your question!
Yes, in function GT2DetRes in panda_utils.py(line 174), only visible body BBoxes are used to generate detection results. But this function is used to generate 'fake' detection results using ground-truth annotation. In demo.py(line 37), this function is used to generate detection results 'results/mergetest.json' because there is no real detection results to use in DetResMerge. That means, in practical use, you doesn't need to use GT2DetRes because you have real detection results on splited images and you can merge them using DetResMerge. So never mind, this GT2DetRes is designed to generate some intermediate results to demostrate functions. 
I apologize for confusing you by not explaining it clearly in the code.
