### ISSUE TITLE
how to evaluate MOT result on panda without the groundtruth of test scenes?

### ISSUE THREAD

**Issue by boringwar** [GigaVision/PANDA-Toolkit#5]
Hi, authors, I'm evaluating my tracking algorithm on PANDA dataset. The 'video_anno' folder contains no ground-truth data for the last 5 scenes. I am wondering how to evaluate the result to compare with your baselines in CVPR 2020 paper "PANDA: A Gigapixel-level Human-centric Video Dataset".

**Comment by DarkstartsUp** [comment]
Sorry, we are holding the international AI competition (track 2) recently. In order to ensure the fairness of the competition, we have temporarily closed the test set result submission channel. MOT is the second round of the competition. You can submit the results on the competition page after the second round begins (April. 15th). Please refer to the competition page (https://gaiic.tianchi.aliyun.com) for details.
